### PR TITLE
Gvt 165

### PR DESCRIPTION
**Pull request by hyungman**
A brief summary of what have been updated and the instruction for running test scripts:

* Enabled color for the following apps
- gvtPly, gvtPlyNS, gvtFileLoad, glTracer

* Added bash scripts for regression testing
All scripts are under Test/regression/cpp.

* Rendered following PLY/OBJ scenes
Enzo black and white
Enzo color (used temperature as color map)
Richtmyer-Meshkov color (used gradients as color map)
Cornell boxes
WS2 bonds

* Tested each application under various settings:
image scheduler
domain scheduler
embree adapter
embree-stream adapter

* Bug fix
There was a minor bug in GraviT image compositer which generated a PPM file with incorrect green color channel (i.e RBB, not RGB)

* Open issue
When rendering Cornell boxes even with 1 sample per pixel and 1 bounce per ray, an image artifact is created (i.e. concentric circular bands). I suspect the artifact is caused by clipping pixel values in the middle of the ray tracing stage. If this is true, we need to use a high dynamic range for pixel values and apply some sort of tone mapping at the end prior to updating the frame buffer.

* Instruction for testing

Part 1. Test film mode

1. Set the models to render
export GVT_MODELS="/work/03378/hpark/maverick/gvtmodels"

2. Assuming GVT_HOME is your local gravit clone, run the test script for testing film mode.
$GVT_HOME/Test/regression/cpp/test_cpp_singlenode_all.sh

3. Manually inspect all generated ppm files. (To be automated)

Part 2. Test interactive mode

4. Run the test script for testing interactive mode.
vglrun $GVT_HOME/Test/regression/cpp/test_cpp_singlenode_gl_all.sh

5. Manually inspect what is in the viewer.

6. Keep typing the letter q to invoke next tests.
  As of now, there is no option in GLTrace.cpp to set the number of frames to render so we need to interactively quit between tests.

Enjoy the colored scenes!

### CODE REVIEW

**Comment by semeraro** [comment]
Thanks  Hyungman! This is quite a bit of work.

Dave Semeraro
Visualization Group
Texas Advanced Computing Center
University of Texas Austin

**Comment by hyungman** [comment]
Please let me know if you can't cd into the following. I've only given access to the groups I belong to.
/work/03378/hpark/maverick/gvtmodels

**Comment by hyungman** [comment]
Thanks for you comment, Dave! I only tested them on a single node, though. A lot ahead for MPI!

**Comment by semeraro** [comment]
Hi Hyungman. I can not get into that directory. I am in group G-80871 if you want to open to that group. I don’t know how you want to work it.

Dave Semeraro
Visualization Group
Texas Advanced Computing Center
University of Texas Austin

**Comment by hyungman** [comment]
Dave,

Can you try again? I even gave read access to other.

Hyungman

**Comment by pnav** [comment]
Hyungman,

Please mark it for G-814944, which is the GraviT group.
One issue is that your $WORK directory itself is not open. Please give at least execute permission to $WORK . If you do that for all (chmod a+x $WORK) then folks with exact paths can access foo but cannot generally read the directory contents.

Paul



On Jun 8, 2017, at 10:44 AM, dave semeraro <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Hyungman. I can not get into that directory. I am in group G-80871 if you want to open to that group. I don’t know how you want to work it.

Dave Semeraro
Visualization Group
Texas Advanced Computing Center
University of Texas Austin

**Comment by hyungman** [comment]
Thanks, Paul! You should be able to read now. I gave access to G-814944.

**Review by jgbarbosa — APPROVED** [review]

**Pull request merged**
